<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accedi</name>
   <tag></tag>
   <elementGuidId>508f701b-b448-4abf-b928-72d88c42006b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.buttons.accedi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24d3bfc0-a6b7-49c0-93b5-933e38c7849f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9e9425a9-3636-4c44-94ec-e7c0e9cf7545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttons accedi</value>
      <webElementGuid>8d079c98-8d9d-4eb0-8121-4aeb8a2cce97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accedi</value>
      <webElementGuid>c17213d0-e120-4ca7-9382-030faef8e5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-content&quot;]/div[@class=&quot;bg-imgmobile&quot;]/section[@class=&quot;mid-align&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row ipad-reverse&quot;]/div[@class=&quot;col-md-7 widfuipad&quot;]/form[1]/div[@class=&quot;registrati-form&quot;]/div[@class=&quot;text-center&quot;]/button[@class=&quot;buttons accedi&quot;]</value>
      <webElementGuid>28f7a2ec-85ae-4718-afcb-8db8b0ef662a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>44df974e-a614-42f0-bce5-58181e87d4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div[2]/form/div/div[3]/button</value>
      <webElementGuid>78dd7d83-dab2-429e-a998-dc92f84d2b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>4abd24f5-0c1c-4f2c-ada2-e8f00648921a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Accedi' or . = 'Accedi')]</value>
      <webElementGuid>cfb0c7c1-4826-4b97-92cc-58059ff7a449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
