<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3 ways community creates a healthy life</name>
   <tag></tag>
   <elementGuidId>49dc1b72-7f17-4ffb-9c55-86924380437d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-header.percorso-header.cursor-pointer.percorso-header-new.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordion']/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '3 ways community creates a healthy life' or . = '3 ways community creates a healthy life')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07ba3052-f921-4992-85f7-dd893100972b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header percorso-header cursor-pointer percorso-header-new collapsed</value>
      <webElementGuid>e7654868-0480-4732-825d-80f3a902c6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3 ways community creates a healthy life</value>
      <webElementGuid>7c0c613b-711e-4de7-8cfc-c5712c5399b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion&quot;)/div[@class=&quot;iapdwful p-r15&quot;]/div[@class=&quot;card mb-0&quot;]/div[@class=&quot;bot-lini&quot;]/div[@class=&quot;course-content-list&quot;]/div[@class=&quot;card-header percorso-header cursor-pointer percorso-header-new collapsed&quot;]</value>
      <webElementGuid>cde8b990-865d-4e1c-8505-f6232f6d4719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>1453ae78-93c2-4da1-9964-554a3dd19d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse_0_0</value>
      <webElementGuid>29ab176b-861c-42d5-be87-713a1c7e8bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42b67ede-8f23-43b8-8dc2-864720939168</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div/div/div[2]/div</value>
      <webElementGuid>0fa37f5b-a97a-4f6a-a292-480f19014dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>b3b82782-07ba-46fd-8320-2eb531a316ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '3 ways community creates a healthy life' or . = '3 ways community creates a healthy life')]</value>
      <webElementGuid>8a6bc122-5bb6-4b9e-9bf3-b2b0671186c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div/div/div[2]/div/div</value>
      <webElementGuid>12e5a8aa-2023-4f9c-8a05-2cc0064d3993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div</value>
      <webElementGuid>7f3b6d8e-a4b7-45f7-b81a-956a7df3d746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
