<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Vital parameters</name>
   <tag></tag>
   <elementGuidId>87472c9a-72b5-4e13-9dc2-3ef126b0b5e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dashboard > div.align-j > h4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dashboard']/div/h4</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Vital parameters' or . = 'Vital parameters')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>7af9507c-27bc-4574-aec1-07606ec9c76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vital parameters</value>
      <webElementGuid>38ca57b3-9766-4759-b02b-70d311823679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[@class=&quot;align-j&quot;]/h4[1]</value>
      <webElementGuid>4c7f92a8-e46e-4a9d-a8c5-c4531cb0f875</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard']/div/h4</value>
      <webElementGuid>bf49303c-c77d-4e02-bb57-9013d0aebe5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/h4</value>
      <webElementGuid>2d74307f-a7ec-49bd-b41b-9adfed13dd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Vital parameters' or . = 'Vital parameters')]</value>
      <webElementGuid>3a235ae4-b952-4de3-a838-269a7ea3b918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
