<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ad535337-4cfa-4405-b28c-96893c6d449a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.table-action > img[alt=&quot;icon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='test']/div/div/div[2]/table/tbody/tr/td[6]/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f15f45e4-de53-4903-8493-1a779200a455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/expand-icon.3e048877.svg</value>
      <webElementGuid>4f7e8e49-552a-4763-a0d8-8f0b25e80db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>939aade9-dbaf-496f-9edf-897618af7fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test&quot;)/div[1]/div[1]/div[@class=&quot;react-bootstrap-table table-responsive mt-4&quot;]/table[@class=&quot;table table-bordered&quot;]/tbody[1]/tr[1]/td[6]/div[@class=&quot;d-flex justify-content-center&quot;]/button[@class=&quot;table-action&quot;]/img[1]</value>
      <webElementGuid>3c7b3dc9-fe53-4273-b97e-ba53774d5c49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='test']/div/div/div[2]/table/tbody/tr/td[6]/div/button/img</value>
      <webElementGuid>ade27f66-795c-4160-89e8-9c1ca9210767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[16]</value>
      <webElementGuid>4ade9640-8f05-4891-86cc-ed4724c5f30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button/img</value>
      <webElementGuid>222f9896-eff3-409e-8788-06cb4133d033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/expand-icon.3e048877.svg' and @alt = 'icon']</value>
      <webElementGuid>4b18e473-3169-4954-979d-d1f1b94daea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[15]</value>
      <webElementGuid>25737652-193b-4ee6-8b09-1d2708bd142c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
