<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>9438ec57-3e04-4689-892f-8800a2b6f928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>813961dc-2c52-4152-b0e4-63488e0939e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>af17dd3f-cce4-4431-85c6-aaccc5cfca30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User ID</value>
      <webElementGuid>01c634f9-26bf-47db-b292-f9877fd9d349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4a69d996-fdf5-410a-8cb1-2fc27bd88caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>24d96109-2675-4a48-ad7f-2e985afd5e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>hemant.uchchasare@5exceptions.com</value>
      <webElementGuid>2043eedf-25c8-42f5-aa2f-cf2e8a830174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-content&quot;]/div[@class=&quot;bg-imgmobile&quot;]/section[@class=&quot;mid-align&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row ipad-reverse&quot;]/div[@class=&quot;col-md-7 widfuipad&quot;]/form[1]/div[@class=&quot;registrati-form&quot;]/div[@class=&quot;form-group relative&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>71dfc898-96b1-42b7-82e7-3d7c6c3ee539</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>26044935-e113-49cf-970e-2dad9b9659a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/section/div/div/div[2]/form/div/div/input</value>
      <webElementGuid>9d6a7682-9872-4f97-9551-29e8c144c624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4dcb4d3f-b86f-4f46-95d0-7c3c3aeee9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'User ID' and @name = 'email']</value>
      <webElementGuid>f28da8ea-e10e-467e-93b9-24e962fe8e24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
