<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Maintaining a healthy weight takes more t_cdcf93</name>
   <tag></tag>
   <elementGuidId>b8dd9102-181d-4e71-8621-653b49ca5daf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.course-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapse_0_0']/div/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${Text}' or . = '${Text}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>781fbc75-2f86-4e8d-9a06-42081dd5ca80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>course-title</value>
      <webElementGuid>ac136a76-c4e7-43c5-9084-d120f17ba6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${Text}</value>
      <webElementGuid>12075a77-4621-4fa6-98d7-3ac8d6b1883c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapse_0_0&quot;)/div[@class=&quot;d-flex align-items-start cursor-pointer&quot;]/p[@class=&quot;course-title&quot;]</value>
      <webElementGuid>089ddbd0-de01-4baf-9242-aea5f202b5f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapse_0_0']/div/p</value>
      <webElementGuid>0648fc9c-5bc2-49a2-8441-139b7c84a5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>f9d7ec19-1488-4daa-9348-0e7af38938a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Maintaining a healthy weight takes more than diet and exercise, says physical activity epidemiologist Olivia Affuso. In this actionable talk, she shows how you can kickstart a healthy life by tapping into the collective power of a community that supports and motivates your health goals.' or . = 'Maintaining a healthy weight takes more than diet and exercise, says physical activity epidemiologist Olivia Affuso. In this actionable talk, she shows how you can kickstart a healthy life by tapping into the collective power of a community that supports and motivates your health goals.')]</value>
      <webElementGuid>d4ebfe21-4e5d-4e41-95ea-661d1c5153c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
