<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Training</name>
   <tag></tag>
   <elementGuidId>05848efa-a0cf-4801-a409-7cfcaf29946e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/section/div/div/div/div/div/div[2]/ul/div[3]/li/a/span</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Training' or . = 'Training')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8f2ffeff-3c92-40d1-88c1-1b26b6ffb9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ipad-textn p-lefts li-span-new</value>
      <webElementGuid>2540098e-4635-450d-8251-58211cfcc2ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Training</value>
      <webElementGuid>7c880f7f-9abf-43fd-8a7d-4acc7fa878d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-content&quot;]/section[@class=&quot;full_bg dashboard-mobile dashboard-section&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2 p-0 darkimenu none-viewport ipad-widhset&quot;]/div[@class=&quot;left-dashboard text&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;navigate-new navigate manageside-bar&quot;]/ul[1]/div[@class=&quot;profile-line&quot;]/li[1]/a[1]/span[@class=&quot;ipad-textn p-lefts li-span-new&quot;]</value>
      <webElementGuid>453c2ba9-4422-4b46-aa88-cb1c615a0e7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div/div/div/div/div[2]/ul/div[3]/li/a/span</value>
      <webElementGuid>b7817395-fbf4-430b-8505-c971e8bffaf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/li/a/span</value>
      <webElementGuid>2eaf0624-8a5c-4917-8616-0e7d9311c96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Training' or . = 'Training')]</value>
      <webElementGuid>e9c09193-10f0-4a27-a7e0-6ef892297661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/section/div/div/div/div/div/div/ul/li[5]/a/span</value>
      <webElementGuid>a48da61d-e510-4c0d-a028-b728baa7ca2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>ba250cc7-28fc-4633-95f5-f7110523e4a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
