<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_measurement-canvas</name>
   <tag></tag>
   <elementGuidId>8ba1e5e6-0db1-4ece-a87d-811a5fd87639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>video.measurement-canvas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div[2]/div/video</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[@class=&quot;main-body&quot;]/div[@class=&quot;sc-aXZVg sc-fqkvVR gLEhKM ewVhje&quot;]/div[@class=&quot;sc-aXZVg sc-gsFSXq sc-kAyceB fohVZx jiQZuX coZMEn&quot;]/div[@class=&quot;sc-aXZVg iUOLqQ&quot;]/div[@class=&quot;sc-aXZVg gdJJEc&quot;]/video[@class=&quot;measurement-canvas&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>66fc77a8-7140-4f3f-a453-ad80140452e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>640</value>
      <webElementGuid>de2611bc-e7ad-4487-97ba-52c88b14d582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>520</value>
      <webElementGuid>1c8f2905-23f4-4dc5-849a-2daed44ddd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>measurement-canvas</value>
      <webElementGuid>478573a6-955d-47ac-ba2a-3751d527e354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main-body&quot;]/div[@class=&quot;sc-aXZVg sc-fqkvVR gLEhKM ewVhje&quot;]/div[@class=&quot;sc-aXZVg sc-gsFSXq sc-kAyceB fohVZx jiQZuX coZMEn&quot;]/div[@class=&quot;sc-aXZVg iUOLqQ&quot;]/div[@class=&quot;sc-aXZVg gdJJEc&quot;]/video[@class=&quot;measurement-canvas&quot;]</value>
      <webElementGuid>7335fa85-7e80-47cf-8ef7-233f7a0a5745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[2]/div/video</value>
      <webElementGuid>34ad2150-1175-4e5a-aec6-b48248c44fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>0e19bf4c-7513-46a6-ad6a-703ce15e13b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
