<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>93f38fad-fc5a-4c01-bdb1-ce645c826646</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ted-player']/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.absolute.left-0.top-0.h-full.w-full.bg-black > div:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9a3570c7-6229-4ef4-9100-78d99f93748b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ted-player&quot;)/div[@class=&quot;absolute left-0 top-0 h-full w-full bg-black&quot;]/div[@class=&quot;absolute left-0 top-0 h-full w-full bg-black&quot;]/div[2]</value>
      <webElementGuid>0eea22ba-3a73-4a45-b155-9795c0add97d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ted-player']/div/div/div[2]</value>
      <webElementGuid>5477deee-25bd-4300-9ca3-2093e6a91b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>97bfd190-ef77-4c1f-9b76-90d3fe0a2747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
